### ISSUE TITLE
can not run proc_sisimp.py in default mode

### ISSUE THREAD

**Issue by alihakimi68** [CNES/swot-hydrology-toolbox#15]
In July 2023 I ran SWOT hydrology toolbox on a virtual linux and it worked fine with no problem.
Today I want to run it again, when I run command
$ python $SWOT_HYDROLOGY_TOOLBOX/sisimp/proc_sisimp.py rdf/parameter_sisimp.rdf
I receive an error:

Traceback (most recent call last):
  File "/home/optimus/swot-hydrology-toolbox/sisimp/proc_sisimp.py", line 25, in <module>
    import sisimp_processing as sisimp_ps
  File "/home/optimus/swot-hydrology-toolbox/sisimp/sisimp_processing.py", line 35, in <module>
    import sisimp_function as sisimp_fct
  File "/home/optimus/swot-hydrology-toolbox/sisimp/sisimp_function.py", line 24, in <module>
    import write_polygons as write_poly
  File "/home/optimus/swot-hydrology-toolbox/sisimp/write_polygons.py", line 41, in <module>
    import proc_pixc
  File "/home/optimus/swot-hydrology-toolbox/sisimp/proc_pixc.py", line 24, in <module>
    import product_netcdf as my_nc
  File "/home/optimus/swot-hydrology-toolbox/sisimp/product_netcdf.py", line 22, in <module>
    import cnes.common.lib.my_netcdf_file as my_nc
ModuleNotFoundError: No module named 'cnes'

the orbits are created successfully and I checked them in a GIS software. 
![Screenshot from 2023-09-14 09-27-07](https://github.com/CNES/swot-hydrology-toolbox/assets/120417588/8691eaeb-b03f-4b7f-9e7c-3b8c5a39d324)

**Comment by alihakimi68** [comment]
There is a list of requirements in: processing/src/cnes/sas/requirements.txt
that should be installed. And that will fix the problem.
